version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpassword
    ports:
      - "9000:9000"
    command: server /data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
